#!/bin/bash

# Avoid memory allocation errors
sudo mount -o remount,size=128M /dev/shm

# increase cpu performance
echo -n performance | sudo tee /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

# disable networking
echo -n "1-1.1:1.0" | sudo tee /sys/bus/usb/drivers/smsc95xx/unbind
sudo service networking stop

# disable unused services
sudo service triggerhappy stop

# get around the fact we have no X session
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket

# start jackd
jackd -d alsa -d hw:0 &>/tmp/jackd.out &

sleep 1

# start fluidsynth
fluidsynth --server --no-shell --audio-driver=jack \
  --connect-jack-outputs --reverb=0 --chorus=0 --gain=0.8 \
  /usr/share/sounds/sf2/FluidR3_GM.sf2 \
  &>/tmp/fluidsynth.out &

# wait for jackd/fluidsynth to start
sleep 10

# connect our keyboard MIDI input to the fluidsynth output
aconnect 20:0 128:0
